# Generated by Django 2.0.5 on 2018-09-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='choiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=20)),
                ('option2', models.CharField(max_length=20)),
                ('option3', models.CharField(max_length=20)),
                ('option4', models.CharField(max_length=20)),
                ('answer', models.CharField(choices=[('opt1', models.CharField(max_length=20)), ('opt2', models.CharField(max_length=20)), ('opt3', models.CharField(max_length=20)), ('opt4', models.CharField(max_length=20))], max_length=20)),
                ('stmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueAns.QuesModel')),
            ],
        ),
    ]
