# Generated by Django 2.0.5 on 2018-09-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0002_choicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('ING', 'ING')], default='MCQ', max_length=5),
        ),
    ]
