# Generated by Django 2.0.5 on 2018-09-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0004_auto_20180907_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourchoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=20)),
                ('stmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueAns.QuesModel')),
            ],
        ),
    ]
