# Generated by Django 2.0.5 on 2018-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0005_yourchoicemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansmodel',
            name='stmt',
        ),
        migrations.RenameField(
            model_name='choicemodel',
            old_name='stmt',
            new_name='q',
        ),
        migrations.AddField(
            model_name='yourchoicemodel',
            name='ans',
            field=models.CharField(default='MCQ', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnsModel',
        ),
    ]
