# Generated by Django 2.0.5 on 2018-09-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0006_auto_20180907_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourchoicemodel',
            name='ans',
            field=models.CharField(max_length=20, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='yourchoicemodel',
            name='choice',
            field=models.CharField(max_length=20, verbose_name='Your Ans'),
        ),
    ]
