# Generated by Django 2.0.5 on 2018-09-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0007_auto_20180907_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourchoicemodel',
            name='choice',
            field=models.CharField(max_length=20, null='True', verbose_name='Your Ans'),
        ),
    ]
