# Generated by Django 2.0.5 on 2018-09-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0008_auto_20180907_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourchoicemodel',
            name='choice',
            field=models.CharField(blank='True', default='1', max_length=20, verbose_name='Your Ans'),
        ),
    ]
