# Generated by Django 2.0.5 on 2018-09-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0009_auto_20180908_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourchoicemodel',
            name='ans',
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='ans',
            field=models.IntegerField(choices=[('1', models.CharField(max_length=20)), ('2', models.CharField(max_length=20)), ('3', models.CharField(max_length=20)), ('4', models.CharField(max_length=20))], default=0, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='yourchoicemodel',
            name='ans_c',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='QueAns.choiceModel'),
        ),
    ]
