# Generated by Django 2.0.5 on 2018-09-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0010_auto_20180908_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodel',
            name='ans',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0, verbose_name='Answer'),
        ),
    ]
